Connected to Python 3.11.5

In [5]:
import pandas as pd
import numpy as np
from src_fhb import EDA

In [6]:
dataset = EDA.leer_csv('finanzas-hotel-bookings.csv')
dataset

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,0
0,Resort Hotel,False,342.000000,2015.0,July,27.0,1.0,0.000000,0.000000,2.0,NaN,0.0,BB,PRT,NaN,Direct,0.0,NaN,0.0,C,C,3.0,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01 00:00:00,NaN
1,Resort Hotel,False,737.000000,NaN,July,27.0,1.0,0.000000,0.000000,2.0,NaN,0.0,BB,NaN,NaN,Direct,0.0,0.0,0.0,NaN,C,4.0,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01 00:00:00,NaN
2,Resort Hotel,False,7.000000,2015.0,July,27.0,1.0,0.000000,1.000000,1.0,0.0,0.0,BB,GBR,NaN,Direct,0.0,0.0,0.0,A,C,0.0,NaN,NaN,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02 00:00:00,NaN
3,Resort Hotel,False,13.000000,NaN,July,27.0,1.0,0.000000,1.000000,1.0,NaN,0.0,BB,GBR,Corporate,Corporate,0.0,0.0,0.0,A,A,0.0,304.0,NaN,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02 00:00:00,NaN
4,Resort Hotel,False,14.000000,NaN,July,NaN,1.0,0.000000,2.000000,2.0,NaN,0.0,BB,NaN,Online TA,TA/TO,0.0,0.0,0.0,A,A,0.0,240.0,NaN,0.0,Transient,98.0,0.0,1.0,Check-Out,2015-07-03 00:00:00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182872,NaN,NaN,224.337762,NaN,NaN,NaN,NaN,19.005545,19.819823,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182873,NaN,NaN,390.141963,NaN,NaN,NaN,NaN,14.751794,19.989726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182874,NaN,NaN,230.689826,NaN,NaN,NaN,NaN,11.409496,20.461372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182875,NaN,NaN,304.888534,NaN,NaN,NaN,NaN,16.744472,15.400773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182876,NaN,NaN,341.238166,NaN,NaN,NaN,NaN,17.791486,24.442690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
EDA.exploracion_df(dataset)

 Filas y Columnas del DATAFRAME

El número de filas que tenemos es de 182877.
El número de columnas es de 32

____________________________________________________________

 Nombre de todas las Columnas del DATAFRAME:

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', '0'],
      dtype='object')
____________________________________________________________

INFORMACIÓN GENERAL DEL DATAFRAME

<class 'pandas.core.frame.DataFrame'>
Index: 182877 entries, 0 to 182876
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119490 non-null  float64
 3   arrival_date_year               64829 non-null   float64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        101004 non-null  float64
 6   arrival_date_day_of_month       119271 non-null  float64
 7   stays_in_weekend_nights         119490 non-null  float64
 8   stays_in_week_nights            119490 non-null  float64
 9   adults                          119428 non-null  float64
 10  children                        69302 non-null   float64
 11  babies                          119431 non-null  float64
 12  meal                            119390 non-null  object
 13  country                         65054 non-null   object
 14  market_segment                  59934 non-null   object
 15  distribution_channel            105899 non-null  object
 16  is_repeated_guest               114376 non-null  float64
 17  previous_cancellations          76228 non-null   float64
 18  previous_bookings_not_canceled  119390 non-null  float64
 19  reserved_room_type              79275 non-null   object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119418 non-null  float64
 22  agent                           103050 non-null  float64
 23  company                         3870 non-null    float64
 24  days_in_waiting_list            119390 non-null  float64
 25  customer_type                   94199 non-null   object
 26  adr                             119390 non-null  float64
 27  required_car_parking_spaces     119390 non-null  float64
 28  total_of_special_requests       119390 non-null  float64
 29  reservation_status              119390 non-null  object
 30  reservation_status_date         106514 non-null  object
 31  0                               42951 non-null   object
dtypes: float64(19), object(13)
memory usage: 46.0+ MB
None
____________________________________________________________

Ver los NULOS del DataFrame

Los nulos: --> 8175846.875

La columna hotel: 34.71568321877546
La columna is_canceled: 34.71568321877546
La columna lead_time: 34.661001656851326
La columna arrival_date_year: 64.55049022020265
La columna arrival_date_month: 34.71568321877546
La columna arrival_date_week_number: 44.76943519414689
La columna arrival_date_day_of_month: 34.78075427746518
La columna stays_in_weekend_nights: 34.661001656851326
La columna stays_in_week_nights: 34.661001656851326
La columna adults: 34.69490422524429
La columna children: 62.1045839553361
La columna babies: 34.693263778386566
La columna meal: 34.71568321877546
La columna country: 64.42745670587334
La columna market_segment: 67.22715267638904
La columna distribution_channel: 42.09277273796049
La columna is_repeated_guest: 37.45741673365158
La columna previous_cancellations: 58.31733897647052
La columna previous_bookings_not_canceled: 34.71568321877546
La columna reserved_room_type: 56.651191784642144
La columna assigned_room_type: 34.71568321877546
La columna booking_changes: 34.70037238143671
La columna agent: 43.65065043717909
La columna company: 97.88382355353599
La columna days_in_waiting_list: 34.71568321877546
La columna customer_type: 48.49051548308426
La columna adr: 34.71568321877546
La columna required_car_parking_spaces: 34.71568321877546
La columna total_of_special_requests: 34.71568321877546
La columna reservation_status: 34.71568321877546
La columna reservation_status_date: 41.75648113212706
La columna 0: 76.51372233796486
____________________________________________________________

Valores ÚNICOS por columna:

La columna hotel: 3
La columna hotel: ['Resort Hotel' 'City Hotel' nan]
La columna is_canceled: 3
La columna is_canceled: [False True nan]
La columna lead_time: 580
La columna lead_time: [342.         737.           7.          13.          14.
   0.           9.          85.          75.          23.
  35.          68.          18.          37.          12.
  72.         127.          78.          48.          60.
  77.          99.         118.          95.          96.
  69.          45.          40.          15.          36.
  43.          70.          16.         107.          47.
 113.          90.          50.          93.          76.
   3.           1.          10.           5.          17.
  51.          71.          63.          62.         101.
   2.          81.         368.         364.         324.
  79.          21.         109.         102.           4.
  98.          92.          26.          73.         115.
  86.          52.          29.          30.          33.
  32.           8.         100.          44.          80.
  97.          64.          39.          34.          27.
  82.          94.         110.         111.          84.
  66.         104.          28.         258.         112.
  65.          67.          55.          88.          54.
 292.          83.         105.         280.         394.
  24.         103.         366.         249.          22.
  91.          11.         108.         106.          31.
  87.          41.         304.         117.          59.
  53.          58.         116.          42.         321.
  38.          56.          49.         317.           6.
  57.          19.          25.         315.         123.
  46.          89.          61.         312.         299.
 130.          74.         298.         119.          20.
 286.         136.         129.         124.         327.
 131.         460.         140.         114.         139.
 122.         137.         126.         120.         128.
 135.         150.         143.         151.         132.
 125.         157.         147.         138.         156.
 164.         346.         159.         160.         161.
 333.         381.         149.         154.         297.
 163.         314.         155.         323.         340.
 356.         142.         328.         144.         336.
 248.         302.         175.         344.         382.
 146.         170.         166.         338.         167.
 310.         148.         165.         172.         171.
 145.         121.         178.         305.         173.
 152.         354.         347.         158.         185.
 349.         183.         352.         177.         200.
 192.         361.         207.         174.         330.
 134.         350.         334.         283.         153.
 197.         133.         241.         193.         235.
 194.         261.         260.         216.         169.
 209.         238.         215.         141.         189.
 187.         223.         284.         214.         202.
 211.         168.         230.         203.         188.
 232.         709.         219.         162.         196.
 190.         259.         228.         176.         250.
 201.         186.         199.         180.         206.
 205.         224.         222.         182.         210.
 275.         212.         229.         218.         208.
 191.         181.         179.         246.         255.
 226.         288.         253.         252.         262.
 236.         256.         234.         254.         468.
 213.         237.         198.         195.         239.
 263.         265.         274.         217.         220.
 307.         221.         233.         257.         227.
 276.         225.         264.         311.         277.
 204.         290.         266.         270.         294.
 319.         282.         251.         322.         291.
 269.         240.         271.         184.         231.
 268.         247.         273.         300.         301.
 267.         244.         306.         293.         309.
 272.         242.         295.         285.         243.
 308.         398.         303.         245.         424.
 279.         331.         281.         339.         434.
 357.         325.         329.         278.         332.
 343.         345.         360.         348.         367.
 353.         373.         374.         406.         400.
 326.         379.         399.         316.         341.
 320.         385.         355.         363.         358.
 296.         422.         390.         335.         370.
 376.         375.         397.         289.         542.
 403.         383.         384.         359.         393.
 337.         362.         365.         435.         386.
 378.         313.         351.         287.         471.
 462.         411.         450.         318.         372.
 371.         454.         532.         445.         389.
 388.         407.         443.         437.         451.
 391.         405.         412.         419.         420.
 426.         433.         440.         429.         418.
 447.         461.         605.         457.         475.
 464.         482.         626.         489.         496.
 503.         510.         517.         524.         531.
 538.         545.         552.         559.         566.
 573.         580.         587.         594.         601.
 608.         615.         622.         629.         396.
 410.         395.         423.         408.         409.
 448.         465.         387.         414.         476.
 479.         467.         490.         493.         478.
 504.         507.         458.         518.         521.
 377.         444.         380.         463.                  nan
 285.39076115 259.60030847 350.5254671  249.23690056 299.65699934
 222.02695972 298.35427899 346.66602497 347.76226048 339.40496071
 389.53687271 393.76634805 314.16036762 364.89775035 243.92395582
 394.3326073  393.40409048 274.25884382 207.26954315 310.5315347
 359.47837238 345.20917849 274.32614895 233.01141762 283.95634896
 203.65774074 244.4893201  327.39561423 247.72927774 280.28619163
 212.58146219 328.71567405 301.36596307 376.13881065 302.28957214
 268.24918757 211.59656401 284.10926924 361.88118942 343.5797993
 342.43531996 218.07382512 307.99556211 248.15503379 251.83008506
 343.64511445 267.94208942 341.26263716 316.8363944  383.94695591
 370.66007781 279.53655462 240.79611889 267.53224844 303.49850729
 307.30733156 216.62247127 316.15969315 245.66191728 240.04322454
 209.0565627  210.76575543 343.70499547 339.46397195 231.66647278
 221.18266495 255.21461804 322.20411817 322.62570879 345.59373035
 221.07145716 271.31526381 250.65134985 380.53870139 328.15710619
 326.28348783 262.0556897  286.56448693 292.16087026 386.74807799
 352.16090681 354.05866877 396.20591467 319.62494547 238.03548168
 372.29442879 300.1189764  231.05953189 208.20350653 243.47154073
 390.30412923 222.7035657  325.95176372 295.61511521 231.48057469
 224.33776182 390.14196299 230.6898256  304.88853431 341.23816575]
La columna arrival_date_year: 4
La columna arrival_date_year: [2015.   nan 2016. 2017.]
La columna arrival_date_month: 16
La columna arrival_date_month: ['July' 'August' 'September' 'October' 'November' 'December' '1' 'January'
 'February' '2' '3' 'March' 'April' 'May' 'June' nan]
La columna arrival_date_week_number: 54
La columna arrival_date_week_number: [27. nan 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43.
 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.  1.  2.  3.  4.  5.  6.  7.  8.
  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26.]
La columna arrival_date_day_of_month: 32
La columna arrival_date_day_of_month: [ 1.  2. nan  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]
La columna stays_in_weekend_nights: 118
La columna stays_in_weekend_nights: [ 0.          1.          2.          4.          3.          6.
 13.          8.          5.          7.         12.          9.
 16.         18.         19.         10.         14.                 nan
 11.20401583 17.95858865 18.2567912  10.54885853 16.33232084 13.84595175
 16.80862539 11.82216655 18.86586275 17.22279014 12.760956   10.15167042
 10.46332451 14.91338236 11.6042344  18.52118296 16.2922789  14.18553261
 10.80563048 17.90682685 17.9040439  19.91471478 12.23500486 14.48008431
 19.67205011 10.14955202 10.80069687 11.98937751 16.80689813 12.86282951
 18.44605745 16.43682263 10.12644249 14.57592838 11.39086752 13.20007294
 17.15627062 14.98305856 17.29938584 17.90252941 16.22831712 13.95515743
 15.32889675 17.35095681 13.22234578 11.90605506 19.25689048 17.43070043
 12.54926869 11.83209485 15.78722554 17.02492003 11.40315114 14.55697847
 14.00625777 11.05466249 13.16442302 10.23930362 15.23868679 18.42035621
 16.08335029 14.79242931 19.55663558 12.89803072 15.47483733 15.0633126
 12.40148587 18.77747638 13.81006175 13.68616815 18.01163962 16.98171814
 19.66962536 19.91294716 19.21393184 19.77626639 13.95243476 13.30834322
 17.17636146 18.03981923 19.36201984 16.06563272 10.48606185 14.66062143
 14.90806899 10.505497   19.71149087 11.09226823 15.81066934 15.42124553
 11.45834359 11.19386224 15.29596943 18.3330153  18.88063688 19.00554533
 14.75179365 11.4094959  16.74447183 17.79148624]
La columna stays_in_week_nights: 136
La columna stays_in_week_nights: [ 0.          1.          2.          3.          4.          5.
 10.         11.          8.          6.          7.         15.
  9.         12.         33.         20.         14.         16.
 21.         13.         30.         19.         24.         40.
 22.         42.         50.         25.         17.         32.
 26.         18.         34.         35.         41.                 nan
 19.14830297 24.50966025 21.58885576 22.772459   20.60555587 24.45205723
 16.62253515 22.47691627 15.27680799 16.2457977  20.98164488 24.37392779
 21.64810509 21.17909591 17.0419185  18.32276451 21.13143014 18.82350032
 24.18439335 23.55385955 16.60470118 22.68332439 19.36190116 23.47612942
 24.32635726 15.50303327 15.25808408 20.83014979 19.2528658  18.55616571
 21.48292115 20.06245625 15.36403939 15.34203868 20.05995282 22.31063053
 24.05293551 20.91856079 15.22169575 23.48974235 23.44028526 18.00197875
 22.42915643 18.50696459 24.4810778  21.83467545 24.88002862 15.30164525
 18.95204764 23.18104145 22.20833114 24.9931465  16.43573722 16.32622714
 22.68288829 22.40222481 17.5501584  20.76482217 16.41646424 15.78203937
 16.7759765  22.8366592  15.95785505 20.72160006 23.71130964 23.3489699
 18.05678059 20.24069537 17.50126945 16.05933347 16.36136961 18.84068375
 22.06579599 18.44380122 15.08607001 19.82863777 19.97791209 23.54330633
 19.6876756  16.22485443 22.75531998 15.92103145 16.9229536  24.7785892
 17.9793042  23.53838486 24.87021062 21.67642284 22.18306775 19.92414067
 23.29122116 18.60063886 24.24605559 20.18132728 16.52346488 19.81982338
 19.98972562 20.46137184 15.4007731  24.44268952]
La columna adults: 31
La columna adults: [ 2.  1. 51.  3. 52. 53. 55. 57. 54. 59.  4. 58. 56. 50. 26. 27.  0. 20.
  6.  5. 10. 16. 19. 11. 13. 15. 14. 12. 18. 17. nan]
La columna children: 15
La columna children: [nan  0.  1.  2. 10. 19.  3. 17. 11. 18. 13. 16. 14. 15. 12.]
La columna babies: 15
La columna babies: [ 0.  1. 18.  2. 17. 13. 15. 16. 12. 10. 11. 19.  9. 14. nan]
La columna meal: 6
La columna meal: ['BB' 'FB' 'HB' 'SC' 'Undefined' nan]
La columna country: 164
La columna country: ['PRT' nan 'GBR' 'USA' 'ESP' 'IRL' 'FRA' 'ROU' 'NOR' 'OMN' 'ARG' 'DEU'
 'CHE' 'GRC' 'NLD' 'DNK' 'RUS' 'POL' 'AUS' 'EST' 'CZE' 'BRA' 'BEL' 'CN'
 'SWE' 'FIN' 'MOZ' 'SVN' 'MAR' 'ITA' 'UKR' 'SMR' 'LVA' 'PRI' 'CHL' 'CHN'
 'LTU' 'LUX' 'AUT' 'TUR' 'MEX' 'ZAF' 'AGO' 'ISR' 'IND' 'CYM' 'ZMB' 'CPV'
 'ZWE' 'DZA' 'KOR' 'HUN' 'ARE' 'TUN' 'JAM' 'ALB' 'HRV' 'HKG' 'AND' 'GIB'
 'URY' 'BLR' 'JEY' 'CYP' 'MDV' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'COL'
 'SEN' 'GEO' 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MYS' 'VEN' 'ARM' 'LKA' 'CUB'
 'CMR' 'IRN' 'BIH' 'NGA' 'COM' 'BGR' 'CIV' 'SRB' 'JOR' 'SYR' 'BDI' 'SGP'
 'KWT' 'PLW' 'QAT' 'SVK' 'SUR' 'MLT' 'MWI' 'MDG' 'ISL' 'JPN' 'CAF' 'TGO'
 'TWN' 'DJI' 'VNM' 'PER' 'EGY' 'SAU' 'KNA' 'ETH' 'ECU' 'IRQ' 'KHM' 'MCO'
 'BGD' 'TJK' 'NIC' 'GGY' 'BEN' 'VGB' 'CRI' 'TZA' 'GAB' 'MKD' 'TMP' 'GLP'
 'LIE' 'GNB' 'MAC' 'IMN' 'UMI' 'MYT' 'GHA' 'FRO' 'MMR' 'PAN' 'MUS' 'LBY'
 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'DMA' 'UGA' 'MNE' 'GTM' 'ASM' 'KEN'
 'NCL' 'STP' 'KIR' 'SDN' 'ATF' 'SLE' 'SLV' 'LAO']
La columna market_segment: 9
La columna market_segment: [nan 'Corporate' 'Online TA' 'Direct' 'Offline TA/TO' 'Groups'
 'Complementary' 'Undefined' 'Aviation']
La columna distribution_channel: 6
La columna distribution_channel: ['Direct' 'Corporate' 'TA/TO' nan 'Undefined' 'GDS']
La columna is_repeated_guest: 3
La columna is_repeated_guest: [ 0. nan  1.]
La columna previous_cancellations: 22
La columna previous_cancellations: [nan  0. 14. 10. 19. 13. 17.  1.  2.  3. 26. 25.  4. 24. 12. 16.  5. 11.
 15. 18. 21.  6.]
La columna previous_bookings_not_canceled: 74
La columna previous_bookings_not_canceled: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 20. 21. 22. 23. 24. 25. 27. 28. 29. 30. 19. 26. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. nan]
La columna reserved_room_type: 11
La columna reserved_room_type: ['C' nan 'A' 'D' 'E' 'G' 'F' 'H' 'L' 'P' 'B']
La columna assigned_room_type: 13
La columna assigned_room_type: ['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H' 'P' 'L' 'K' nan]
La columna booking_changes: 23
La columna booking_changes: [ 3.  4.  0.  1.  2.  5. 17. 18.  6. 14. 15. 10. 11.  8.  7. 16. 19. 12.
  9. 13. 20. 21. nan]
La columna agent: 334
La columna agent: [ nan 304. 240. 303.  15. 241.   8. 250. 115.   5. 175. 134. 156. 243.
 242.   3. 105.  40. 147. 306. 184.  96.   2. 127.  95. 146.   9. 177.
   6. 143. 244. 149. 167. 300. 171. 305.  67. 196. 152. 142. 261. 104.
  36.  26.  29. 258. 110.  71. 181.  88. 251. 275.  69. 248. 208. 256.
 314. 126. 281. 273. 253. 185. 330. 334. 328. 326. 321. 324. 313.  38.
 155.  68. 335. 308. 332.  94. 348. 310. 339. 375.  66. 327. 387. 298.
  91. 245. 385. 257. 393. 168. 405. 249. 315.  75. 128. 307.  11. 436.
   1. 201. 183. 223. 368. 336. 291. 464. 411. 481.  10. 154. 468. 410.
 390. 440. 495. 492. 493. 434.  57. 531. 420. 483. 526. 472. 429.  16.
 446.  34.  78. 139. 252. 270.  47. 114. 301. 193. 182. 135. 350. 195.
 352. 355. 159. 363. 384. 360. 331. 367.  64. 406. 163. 414. 333. 427.
 431. 430. 426. 438. 433. 418. 441. 282. 432.  72. 450. 180. 454. 455.
  59. 451. 254. 358. 469. 165. 467. 510. 337. 476. 502. 527. 479. 508.
 535. 302. 497. 187.  13.   7.  27.  14.  22.  17.  28.  42.  20.  19.
  45.  37.  61.  39.  21.  24.  41.  50.  30.  54.  52.  12.  44.  31.
  83.  32.  63.  60.  55.  56.  89.  87. 118.  86.  85. 210. 214. 129.

In [8]:
# Crea un diccionario de sustitución
replacement_dict = {1: 'January', 2: 'February', 3: 'March'}

# Aplica la sustitución en la columna 'arrival_date_month'
df['arrival_date_month'] = df['arrival_date_month'].replace(replacement_dict)

# Revisa el DataFrame para asegurarte de que los valores han sido sustituidos
print(df['arrival_date_month'])

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

# Suponiendo que ya tienes el DataFrame cargado en la variable dataset
df = EDA.exploracion_df(dataset)

# Calcula la media de la columna 'children' omitiendo los valores nulos
mean_children = df['children'].mean()

# Sustituye los valores nulos en la columna 'children' por la media calculada
df['children'].fillna(mean_children, inplace=True)

# Revisa el DataFrame para asegurarte de que los valores nulos han sido imputados
print(df['children'])

 Filas y Columnas del DATAFRAME

El número de filas que tenemos es de 182877.
El número de columnas es de 32

____________________________________________________________

 Nombre de todas las Columnas del DATAFRAME:

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'agent', 'company',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', '0'],
      dtype='object')
____________________________________________________________

INFORMACIÓN GENERAL DEL DATAFRAME

<class 'pandas.core.frame.DataFrame'>
Index: 182877 entries, 0 to 182876
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  object
 2   lead_time                       119490 non-null  float64
 3   arrival_date_year               64829 non-null   float64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        101004 non-null  float64
 6   arrival_date_day_of_month       119271 non-null  float64
 7   stays_in_weekend_nights         119490 non-null  float64
 8   stays_in_week_nights            119490 non-null  float64
 9   adults                          119428 non-null  float64
 10  children                        69302 non-null   float64
 11  babies                          119431 non-null  float64
 12  meal                            119390 non-null  object
 13  country                         65054 non-null   object
 14  market_segment                  59934 non-null   object
 15  distribution_channel            105899 non-null  object
 16  is_repeated_guest               114376 non-null  float64
 17  previous_cancellations          76228 non-null   float64
 18  previous_bookings_not_canceled  119390 non-null  float64
 19  reserved_room_type              79275 non-null   object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119418 non-null  float64
 22  agent                           103050 non-null  float64
 23  company                         3870 non-null    float64
 24  days_in_waiting_list            119390 non-null  float64
 25  customer_type                   94199 non-null   object
 26  adr                             119390 non-null  float64
 27  required_car_parking_spaces     119390 non-null  float64
 28  total_of_special_requests       119390 non-null  float64
 29  reservation_status              119390 non-null  object
 30  reservation_status_date         106514 non-null  object
 31  0                               42951 non-null   object
dtypes: float64(19), object(13)
memory usage: 46.0+ MB
None
____________________________________________________________

Ver los NULOS del DataFrame

Los nulos: --> 8175846.875

La columna hotel: 34.71568321877546
La columna is_canceled: 34.71568321877546
La columna lead_time: 34.661001656851326
La columna arrival_date_year: 64.55049022020265
La columna arrival_date_month: 34.71568321877546
La columna arrival_date_week_number: 44.76943519414689
La columna arrival_date_day_of_month: 34.78075427746518
La columna stays_in_weekend_nights: 34.661001656851326
La columna stays_in_week_nights: 34.661001656851326
La columna adults: 34.69490422524429
La columna children: 62.1045839553361
La columna babies: 34.693263778386566
La columna meal: 34.71568321877546
La columna country: 64.42745670587334
La columna market_segment: 67.22715267638904
La columna distribution_channel: 42.09277273796049
La columna is_repeated_guest: 37.45741673365158
La columna previous_cancellations: 58.31733897647052
La columna previous_bookings_not_canceled: 34.71568321877546
La columna reserved_room_type: 56.651191784642144
La columna assigned_room_type: 34.71568321877546
La columna booking_changes: 34.70037238143671
La columna agent: 43.65065043717909
La columna company: 97.88382355353599
La columna days_in_waiting_list: 34.71568321877546
La columna customer_type: 48.49051548308426
La columna adr: 34.71568321877546
La columna required_car_parking_spaces: 34.71568321877546
La columna total_of_special_requests: 34.71568321877546
La columna reservation_status: 34.71568321877546
La columna reservation_status_date: 41.75648113212706
La columna 0: 76.51372233796486
____________________________________________________________

Valores ÚNICOS por columna:

La columna hotel: 3
La columna hotel: ['Resort Hotel' 'City Hotel' nan]
La columna is_canceled: 3
La columna is_canceled: [False True nan]
La columna lead_time: 580
La columna lead_time: [342.         737.           7.          13.          14.
   0.           9.          85.          75.          23.
  35.          68.          18.          37.          12.
  72.         127.          78.          48.          60.
  77.          99.         118.          95.          96.
  69.          45.          40.          15.          36.
  43.          70.          16.         107.          47.
 113.          90.          50.          93.          76.
   3.           1.          10.           5.          17.
  51.          71.          63.          62.         101.
   2.          81.         368.         364.         324.
  79.          21.         109.         102.           4.
  98.          92.          26.          73.         115.
  86.          52.          29.          30.          33.
  32.           8.         100.          44.          80.
  97.          64.          39.          34.          27.
  82.          94.         110.         111.          84.
  66.         104.          28.         258.         112.
  65.          67.          55.          88.          54.
 292.          83.         105.         280.         394.
  24.         103.         366.         249.          22.
  91.          11.         108.         106.          31.
  87.          41.         304.         117.          59.
  53.          58.         116.          42.         321.
  38.          56.          49.         317.           6.
  57.          19.          25.         315.         123.
  46.          89.          61.         312.         299.
 130.          74.         298.         119.          20.
 286.         136.         129.         124.         327.
 131.         460.         140.         114.         139.
 122.         137.         126.         120.         128.
 135.         150.         143.         151.         132.
 125.         157.         147.         138.         156.
 164.         346.         159.         160.         161.
 333.         381.         149.         154.         297.
 163.         314.         155.         323.         340.
 356.         142.         328.         144.         336.
 248.         302.         175.         344.         382.
 146.         170.         166.         338.         167.
 310.         148.         165.         172.         171.
 145.         121.         178.         305.         173.
 152.         354.         347.         158.         185.
 349.         183.         352.         177.         200.
 192.         361.         207.         174.         330.
 134.         350.         334.         283.         153.
 197.         133.         241.         193.         235.
 194.         261.         260.         216.         169.
 209.         238.         215.         141.         189.
 187.         223.         284.         214.         202.
 211.         168.         230.         203.         188.
 232.         709.         219.         162.         196.
 190.         259.         228.         176.         250.
 201.         186.         199.         180.         206.
 205.         224.         222.         182.         210.
 275.         212.         229.         218.         208.
 191.         181.         179.         246.         255.
 226.         288.         253.         252.         262.
 236.         256.         234.         254.         468.
 213.         237.         198.         195.         239.
 263.         265.         274.         217.         220.
 307.         221.         233.         257.         227.
 276.         225.         264.         311.         277.
 204.         290.         266.         270.         294.
 319.         282.         251.         322.         291.
 269.         240.         271.         184.         231.
 268.         247.         273.         300.         301.
 267.         244.         306.         293.         309.
 272.         242.         295.         285.         243.
 308.         398.         303.         245.         424.
 279.         331.         281.         339.         434.
 357.         325.         329.         278.         332.
 343.         345.         360.         348.         367.
 353.         373.         374.         406.         400.
 326.         379.         399.         316.         341.
 320.         385.         355.         363.         358.
 296.         422.         390.         335.         370.
 376.         375.         397.         289.         542.
 403.         383.         384.         359.         393.
 337.         362.         365.         435.         386.
 378.         313.         351.         287.         471.
 462.         411.         450.         318.         372.
 371.         454.         532.         445.         389.
 388.         407.         443.         437.         451.
 391.         405.         412.         419.         420.
 426.         433.         440.         429.         418.
 447.         461.         605.         457.         475.
 464.         482.         626.         489.         496.
 503.         510.         517.         524.         531.
 538.         545.         552.         559.         566.
 573.         580.         587.         594.         601.
 608.         615.         622.         629.         396.
 410.         395.         423.         408.         409.
 448.         465.         387.         414.         476.
 479.         467.         490.         493.         478.
 504.         507.         458.         518.         521.
 377.         444.         380.         463.                  nan
 285.39076115 259.60030847 350.5254671  249.23690056 299.65699934
 222.02695972 298.35427899 346.66602497 347.76226048 339.40496071
 389.53687271 393.76634805 314.16036762 364.89775035 243.92395582
 394.3326073  393.40409048 274.25884382 207.26954315 310.5315347
 359.47837238 345.20917849 274.32614895 233.01141762 283.95634896
 203.65774074 244.4893201  327.39561423 247.72927774 280.28619163
 212.58146219 328.71567405 301.36596307 376.13881065 302.28957214
 268.24918757 211.59656401 284.10926924 361.88118942 343.5797993
 342.43531996 218.07382512 307.99556211 248.15503379 251.83008506
 343.64511445 267.94208942 341.26263716 316.8363944  383.94695591
 370.66007781 279.53655462 240.79611889 267.53224844 303.49850729
 307.30733156 216.62247127 316.15969315 245.66191728 240.04322454
 209.0565627  210.76575543 343.70499547 339.46397195 231.66647278
 221.18266495 255.21461804 322.20411817 322.62570879 345.59373035
 221.07145716 271.31526381 250.65134985 380.53870139 328.15710619
 326.28348783 262.0556897  286.56448693 292.16087026 386.74807799
 352.16090681 354.05866877 396.20591467 319.62494547 238.03548168
 372.29442879 300.1189764  231.05953189 208.20350653 243.47154073
 390.30412923 222.7035657  325.95176372 295.61511521 231.48057469
 224.33776182 390.14196299 230.6898256  304.88853431 341.23816575]
La columna arrival_date_year: 4
La columna arrival_date_year: [2015.   nan 2016. 2017.]
La columna arrival_date_month: 16
La columna arrival_date_month: ['July' 'August' 'September' 'October' 'November' 'December' '1' 'January'
 'February' '2' '3' 'March' 'April' 'May' 'June' nan]
La columna arrival_date_week_number: 54
La columna arrival_date_week_number: [27. nan 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43.
 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.  1.  2.  3.  4.  5.  6.  7.  8.
  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26.]
La columna arrival_date_day_of_month: 32
La columna arrival_date_day_of_month: [ 1.  2. nan  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]
La columna stays_in_weekend_nights: 118
La columna stays_in_weekend_nights: [ 0.          1.          2.          4.          3.          6.
 13.          8.          5.          7.         12.          9.
 16.         18.         19.         10.         14.                 nan
 11.20401583 17.95858865 18.2567912  10.54885853 16.33232084 13.84595175
 16.80862539 11.82216655 18.86586275 17.22279014 12.760956   10.15167042
 10.46332451 14.91338236 11.6042344  18.52118296 16.2922789  14.18553261
 10.80563048 17.90682685 17.9040439  19.91471478 12.23500486 14.48008431
 19.67205011 10.14955202 10.80069687 11.98937751 16.80689813 12.86282951
 18.44605745 16.43682263 10.12644249 14.57592838 11.39086752 13.20007294
 17.15627062 14.98305856 17.29938584 17.90252941 16.22831712 13.95515743
 15.32889675 17.35095681 13.22234578 11.90605506 19.25689048 17.43070043
 12.54926869 11.83209485 15.78722554 17.02492003 11.40315114 14.55697847
 14.00625777 11.05466249 13.16442302 10.23930362 15.23868679 18.42035621
 16.08335029 14.79242931 19.55663558 12.89803072 15.47483733 15.0633126
 12.40148587 18.77747638 13.81006175 13.68616815 18.01163962 16.98171814
 19.66962536 19.91294716 19.21393184 19.77626639 13.95243476 13.30834322
 17.17636146 18.03981923 19.36201984 16.06563272 10.48606185 14.66062143
 14.90806899 10.505497   19.71149087 11.09226823 15.81066934 15.42124553
 11.45834359 11.19386224 15.29596943 18.3330153  18.88063688 19.00554533
 14.75179365 11.4094959  16.74447183 17.79148624]
La columna stays_in_week_nights: 136
La columna stays_in_week_nights: [ 0.          1.          2.          3.          4.          5.
 10.         11.          8.          6.          7.         15.
  9.         12.         33.         20.         14.         16.
 21.         13.         30.         19.         24.         40.
 22.         42.         50.         25.         17.         32.
 26.         18.         34.         35.         41.                 nan
 19.14830297 24.50966025 21.58885576 22.772459   20.60555587 24.45205723
 16.62253515 22.47691627 15.27680799 16.2457977  20.98164488 24.37392779
 21.64810509 21.17909591 17.0419185  18.32276451 21.13143014 18.82350032
 24.18439335 23.55385955 16.60470118 22.68332439 19.36190116 23.47612942
 24.32635726 15.50303327 15.25808408 20.83014979 19.2528658  18.55616571
 21.48292115 20.06245625 15.36403939 15.34203868 20.05995282 22.31063053
 24.05293551 20.91856079 15.22169575 23.48974235 23.44028526 18.00197875
 22.42915643 18.50696459 24.4810778  21.83467545 24.88002862 15.30164525
 18.95204764 23.18104145 22.20833114 24.9931465  16.43573722 16.32622714
 22.68288829 22.40222481 17.5501584  20.76482217 16.41646424 15.78203937
 16.7759765  22.8366592  15.95785505 20.72160006 23.71130964 23.3489699
 18.05678059 20.24069537 17.50126945 16.05933347 16.36136961 18.84068375
 22.06579599 18.44380122 15.08607001 19.82863777 19.97791209 23.54330633
 19.6876756  16.22485443 22.75531998 15.92103145 16.9229536  24.7785892
 17.9793042  23.53838486 24.87021062 21.67642284 22.18306775 19.92414067
 23.29122116 18.60063886 24.24605559 20.18132728 16.52346488 19.81982338
 19.98972562 20.46137184 15.4007731  24.44268952]
La columna adults: 31
La columna adults: [ 2.  1. 51.  3. 52. 53. 55. 57. 54. 59.  4. 58. 56. 50. 26. 27.  0. 20.
  6.  5. 10. 16. 19. 11. 13. 15. 14. 12. 18. 17. nan]
La columna children: 15
La columna children: [nan  0.  1.  2. 10. 19.  3. 17. 11. 18. 13. 16. 14. 15. 12.]
La columna babies: 15
La columna babies: [ 0.  1. 18.  2. 17. 13. 15. 16. 12. 10. 11. 19.  9. 14. nan]
La columna meal: 6
La columna meal: ['BB' 'FB' 'HB' 'SC' 'Undefined' nan]
La columna country: 164
La columna country: ['PRT' nan 'GBR' 'USA' 'ESP' 'IRL' 'FRA' 'ROU' 'NOR' 'OMN' 'ARG' 'DEU'
 'CHE' 'GRC' 'NLD' 'DNK' 'RUS' 'POL' 'AUS' 'EST' 'CZE' 'BRA' 'BEL' 'CN'
 'SWE' 'FIN' 'MOZ' 'SVN' 'MAR' 'ITA' 'UKR' 'SMR' 'LVA' 'PRI' 'CHL' 'CHN'
 'LTU' 'LUX' 'AUT' 'TUR' 'MEX' 'ZAF' 'AGO' 'ISR' 'IND' 'CYM' 'ZMB' 'CPV'
 'ZWE' 'DZA' 'KOR' 'HUN' 'ARE' 'TUN' 'JAM' 'ALB' 'HRV' 'HKG' 'AND' 'GIB'
 'URY' 'BLR' 'JEY' 'CYP' 'MDV' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'COL'
 'SEN' 'GEO' 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MYS' 'VEN' 'ARM' 'LKA' 'CUB'
 'CMR' 'IRN' 'BIH' 'NGA' 'COM' 'BGR' 'CIV' 'SRB' 'JOR' 'SYR' 'BDI' 'SGP'
 'KWT' 'PLW' 'QAT' 'SVK' 'SUR' 'MLT' 'MWI' 'MDG' 'ISL' 'JPN' 'CAF' 'TGO'
 'TWN' 'DJI' 'VNM' 'PER' 'EGY' 'SAU' 'KNA' 'ETH' 'ECU' 'IRQ' 'KHM' 'MCO'
 'BGD' 'TJK' 'NIC' 'GGY' 'BEN' 'VGB' 'CRI' 'TZA' 'GAB' 'MKD' 'TMP' 'GLP'
 'LIE' 'GNB' 'MAC' 'IMN' 'UMI' 'MYT' 'GHA' 'FRO' 'MMR' 'PAN' 'MUS' 'LBY'
 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'DMA' 'UGA' 'MNE' 'GTM' 'ASM' 'KEN'
 'NCL' 'STP' 'KIR' 'SDN' 'ATF' 'SLE' 'SLV' 'LAO']
La columna market_segment: 9
La columna market_segment: [nan 'Corporate' 'Online TA' 'Direct' 'Offline TA/TO' 'Groups'
 'Complementary' 'Undefined' 'Aviation']
La columna distribution_channel: 6
La columna distribution_channel: ['Direct' 'Corporate' 'TA/TO' nan 'Undefined' 'GDS']
La columna is_repeated_guest: 3
La columna is_repeated_guest: [ 0. nan  1.]
La columna previous_cancellations: 22
La columna previous_cancellations: [nan  0. 14. 10. 19. 13. 17.  1.  2.  3. 26. 25.  4. 24. 12. 16.  5. 11.
 15. 18. 21.  6.]
La columna previous_bookings_not_canceled: 74
La columna previous_bookings_not_canceled: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 20. 21. 22. 23. 24. 25. 27. 28. 29. 30. 19. 26. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. nan]
La columna reserved_room_type: 11
La columna reserved_room_type: ['C' nan 'A' 'D' 'E' 'G' 'F' 'H' 'L' 'P' 'B']
La columna assigned_room_type: 13
La columna assigned_room_type: ['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H' 'P' 'L' 'K' nan]
La columna booking_changes: 23
La columna booking_changes: [ 3.  4.  0.  1.  2.  5. 17. 18.  6. 14. 15. 10. 11.  8.  7. 16. 19. 12.
  9. 13. 20. 21. nan]
La columna agent: 334
La columna agent: [ nan 304. 240. 303.  15. 241.   8. 250. 115.   5. 175. 134. 156. 243.
 242.   3. 105.  40. 147. 306. 184.  96.   2. 127.  95. 146.   9. 177.
   6. 143. 244. 149. 167. 300. 171. 305.  67. 196. 152. 142. 261. 104.
  36.  26.  29. 258. 110.  71. 181.  88. 251. 275.  69. 248. 208. 256.
 314. 126. 281. 273. 253. 185. 330. 334. 328. 326. 321. 324. 313.  38.
 155.  68. 335. 308. 332.  94. 348. 310. 339. 375.  66. 327. 387. 298.
  91. 245. 385. 257. 393. 168. 405. 249. 315.  75. 128. 307.  11. 436.
   1. 201. 183. 223. 368. 336. 291. 464. 411. 481.  10. 154. 468. 410.
 390. 440. 495. 492. 493. 434.  57. 531. 420. 483. 526. 472. 429.  16.
 446.  34.  78. 139. 252. 270.  47. 114. 301. 193. 182. 135. 350. 195.
 352. 355. 159. 363. 384. 360. 331. 367.  64. 406. 163. 414. 333. 427.
 431. 430. 426. 438. 433. 418. 441. 282. 432.  72. 450. 180. 454. 455.
  59. 451. 254. 358. 469. 165. 467. 510. 337. 476. 502. 527. 479. 508.
 535. 302. 497. 187.  13.   7.  27.  14.  22.  17.  28.  42.  20.  19.
  45.  37.  61.  39.  21.  24.  41.  50.  30.  54.  52.  12.  44.  31.
  83.  32.  63.  60.  55.  56.  89.  87. 118.  86.  85. 210. 214. 129.

TypeError: 'NoneType' object is not subscriptable